apiVersion: v1
kind: Pod
metadata:
  name: k8s1-pod
  labels:
    app.kubernetes.io/name: k8s1
spec:
  containers:
    - name: k8s1-container1
      image: busybox:1.28
      command: ['sh', '-c', 'echo the app is running! && sleep 3600']
  initContainers:
    - name: init-service
      image: python:alpine
      command: ['python', '-c', 'print("Init container is running python")']
